"""menghapus tabel data

Revision ID: 50d16d0b4795
Revises: 15f30cf61c66
Create Date: 2023-01-27 23:31:46.201876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '50d16d0b4795'
down_revision = '15f30cf61c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_dataUser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_dataUser',
    sa.Column('id', sa.BIGINT(), server_default=sa.text('nextval(\'"tb_dataUser_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tb_dataUser_pkey'),
    sa.UniqueConstraint('id_user', name='tb_dataUser_id_user_key')
    )
    # ### end Alembic commands ###
